#!/usr/bin/env bash
# Initialise the bitbake build directory and write bblayers.conf + local.conf
# for the selected MACHINE / boot device. Idempotent: safe to re-run.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib.sh
source "${HERE}/lib.sh"
# shellcheck source=env.sh
source "${HERE}/env.sh"

[[ -d "${LAYERS_DIR}/poky" ]] || die "layers missing; run scripts/01-fetch-layers.sh first"

# oe-init-build-env creates/uses BUILD_DIR and drops us in it. Run in a subshell
# so we don't pollute the caller, but we only need the side effect (conf/*).
log "Initialising build dir at ${BUILD_DIR} ..."
# oe-init-build-env isn't nounset-safe (e.g. it checks $BBSERVER with no
# default), so relax -u just for this sourced script.
# shellcheck disable=SC1091
( set +u; source "${LAYERS_DIR}/poky/oe-init-build-env" "${BUILD_DIR}" >/dev/null )

CONF="${BUILD_DIR}/conf"
mkdir -p "${CONF}"

# --- bblayers.conf --------------------------------------------------------
log "Writing bblayers.conf ..."
cat > "${CONF}/bblayers.conf" <<EOF
# Autogenerated by scripts/02-configure-build.sh - edits will be overwritten.
POKY_BBLAYERS_CONF_VERSION = "2"
BBPATH = "\${TOPDIR}"
BBFILES ?= ""
BBLAYERS ?= " \\
  ${LAYERS_DIR}/poky/meta \\
  ${LAYERS_DIR}/poky/meta-poky \\
  ${LAYERS_DIR}/poky/meta-yocto-bsp \\
  ${LAYERS_DIR}/meta-openembedded/meta-oe \\
  ${LAYERS_DIR}/meta-openembedded/meta-python \\
  ${LAYERS_DIR}/meta-openembedded/meta-networking \\
  ${LAYERS_DIR}/meta-openembedded/meta-filesystems \\
  ${LAYERS_DIR}/meta-tegra \\
  ${REPO_ROOT}/layers/meta-boat \\
  "
EOF

# --- local.conf -----------------------------------------------------------
# Start from poky's sample, then append our machine-specific fragment guarded
# by a marker so re-runs replace only our block.
SAMPLE="${LAYERS_DIR}/poky/meta-poky/conf/templates/default/local.conf.sample"
[[ -f "${SAMPLE}" ]] || SAMPLE="${LAYERS_DIR}/poky/meta-poky/conf/local.conf.sample"
if [[ ! -f "${CONF}/local.conf" ]]; then
  cp "${SAMPLE}" "${CONF}/local.conf"
fi

MARKER_BEGIN="# >>> xavier-nx-nvme (managed) >>>"
MARKER_END="# <<< xavier-nx-nvme (managed) <<<"
# strip any previous managed block
sed -i "/${MARKER_BEGIN}/,/${MARKER_END}/d" "${CONF}/local.conf"

{
  echo "${MARKER_BEGIN}"
  echo "MACHINE = \"${MACHINE}\""
  # NVIDIA firmware/BSP components ship under proprietary/commercial flags.
  echo 'LICENSE_FLAGS_ACCEPTED += "commercial"'
  # systemd init - appropriate for an always-on embedded/boat computer.
  echo 'INIT_MANAGER = "systemd"'
  # Keep downloads / sstate outside the build dir so re-inits are cheap.
  echo "DL_DIR = \"${WORKROOT}/downloads\""
  echo "SSTATE_DIR = \"${WORKROOT}/sstate-cache\""
  # Delete each recipe's tmp/work/ as soon as it finishes building
  # (outputs live on in sstate-cache/downloads either way). A full
  # image build's work dirs can reach 50GB+ otherwise.
  echo 'INHERIT += "rm_work"'
  # Build parallelism (auto-detected; tune if the host struggles).
  echo 'BB_NUMBER_THREADS ?= "${@oe.utils.cpu_count()}"'
  echo 'PARALLEL_MAKE ?= "-j ${@oe.utils.cpu_count()}"'
  # This host's system GCC (15, defaulting to C23/C++23 with a matching
  # newer libstdc++) is much newer than kirkstone was ever built/tested
  # against: its C23 default breaks old gnulib (m4-native, unzip-native)
  # and K&R-style probes (gmp-native), and LLVM 13 (bundled with rustc
  # 1.59, needed for python3-cryptography's Rust extension) doesn't
  # compile cleanly against a GCC/libstdc++ this new. Rather than patch
  # every old -native recipe one at a time, point -native/-nativesdk
  # builds at gcc-12/g++-12 (`sudo apt-get install gcc-12 g++-12`),
  # matching the GCC generation kirkstone actually expects.
  # Absolute paths: bitbake tasks run with a sanitized PATH (tmp/hosttools,
  # a whitelist of symlinks) that doesn't include arbitrary host binaries
  # like a bare "gcc-12", so a bare name here fails with "No such file or
  # directory" even though it resolves fine in an interactive shell.
  echo 'BUILD_CC = "${CCACHE}/usr/bin/gcc-12 ${BUILD_CC_ARCH}"'
  echo 'BUILD_CXX = "${CCACHE}/usr/bin/g++-12 ${BUILD_CC_ARCH}"'
  echo 'BUILD_CPP = "/usr/bin/gcc-12 ${BUILD_CC_ARCH} -E"'
  echo 'BUILD_CCLD = "/usr/bin/gcc-12 ${BUILD_CC_ARCH}"'
  if [[ -n "${BOOTDEV}" ]]; then
    echo ""
    echo "# --- Boot rootfs from external NVMe storage ---"
    echo "TNSPEC_BOOTDEV = \"${BOOTDEV}\""
    echo "ROOTFSPART_SIZE = \"${ROOTFS_SIZE_BYTES}\""
  fi
  echo "${MARKER_END}"
} >> "${CONF}/local.conf"

log "Configured:"
log "  MACHINE          = ${MACHINE}"
log "  BOOTDEV          = ${BOOTDEV:-<stock SD layout>}"
log "  ROOTFSPART_SIZE  = ${ROOTFS_SIZE_BYTES} bytes"
log "  BUILD_DIR        = ${BUILD_DIR}"
log "Next: scripts/03-build.sh  (builds IMAGE=${IMAGE})"
